version: "3.9"

services:
  es:
    container_name: "e761"
    image: elasticsearch:7.6.1
    ports:
      - "${ES_HTTP_PORT}:9200"
      - "${ES_TCP_PORT}:9300"
    volumes:
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
    restart: always

  logstash:
    container_name: 'l761'
    build: ./logstash
    depends_on:
      - es
    restart: always

  kibana:
    container_name: k761
    image: kibana:7.6.1
    ports:
      - "${Kibana_HTTP_PORT}:5601"
    depends_on:
      - es
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always



